import { StrictMode, createContext, useContext, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import './styles.css'

const AuthContext = createContext(null)
const api = async (url, options = {}) => { const r = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); if (r.status === 204) return null; const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Something went wrong.'); return d }
function AuthProvider({children}) { const [user,setUser]=useState(null),[loading,setLoading]=useState(true); useEffect(()=>{api('/api/auth/me').then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]); return <AuthContext.Provider value={{user,setUser,loading}}>{children}</AuthContext.Provider> }
const useAuth=()=>useContext(AuthContext)
function Navbar(){const {user,setUser}=useAuth();const nav=useNavigate();const logout=async()=>{await api('/api/auth/logout',{method:'DELETE'});setUser(null);nav('/login')};return <header><Link className="brand" to="/">CarePrep</Link><nav>{user ? <><Link to="/appointments">My appointments</Link><Link to="/appointments/new">New appointment</Link><span>{user.email}</span><button className="linkButton" onClick={logout}>Log out</button></> : <><Link to="/login">Log in</Link><Link className="button" to="/register">Create account</Link></>}</nav></header>}
function Protected({children}){const {user,loading}=useAuth();if(loading)return <main><p>Restoring your secure session…</p></main>;return user?children:<Navigate to="/login" replace/>}
function AuthPage({register=false}){const {setUser,user}=useAuth(),nav=useNavigate(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(user)return <Navigate to="/appointments" replace/>;const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const d=await api('/api/auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify({email,password})});setUser(d.user);nav('/appointments')}catch(e){setError(e.message)}finally{setBusy(false)}};return <main className="auth"><section className="card"><h1>{register?'Create your private workspace':'Welcome back'}</h1><p>{register?'Use a password with at least eight characters.':'Log in to prepare for your appointments.'}</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?'Please wait…':register?'Create account':'Log in'}</button></form><p>{register?'Already registered?':'New to CarePrep?'} <Link to={register?'/login':'/register'}>{register?'Log in':'Create an account'}</Link></p></section></main>}
function Appointments(){const [items,setItems]=useState([]),[state,setState]=useState('loading'),[error,setError]=useState('');const load=()=>{setState('loading');api('/api/appointments').then(d=>{setItems(d.appointments);setState('ready')}).catch(e=>{setError(e.message);setState('error')})};useEffect(load,[]);if(state==='loading')return <main><p>Loading appointments…</p></main>;if(state==='error')return <main><p className="error">{error}</p><button onClick={load}>Try again</button></main>;return <main><div className="pageTitle"><div><h1>Your appointments</h1><p>Keep your visit details and questions in one private place.</p></div><Link className="button" to="/appointments/new">Add appointment</Link></div>{items.length===0?<section className="empty"><h2>No appointments yet</h2><p>Create your first appointment, then add the questions you want to discuss.</p><Link className="button" to="/appointments/new">Create appointment</Link></section>:<div className="grid">{items.map(a=><article className="card" key={a.id}><p className="eyebrow">{a.date}</p><h2>{a.provider}</h2><p>{a.visit_type}{a.location&&` · ${a.location}`}</p><Link to={`/appointments/${a.id}`}>Open preparation list →</Link></article>)}</div>}</main>}
const empty={provider:'',visit_type:'General visit',date:'',location:'',notes:''}
function AppointmentForm({initial=empty,onSave}){const [form,setForm]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(form)}catch(e){setError(e.message);setBusy(false)}};return <form className="card form" onSubmit={submit}><label>Provider or clinic<input name="provider" value={form.provider} onChange={change} required/></label><label>Visit type<input name="visit_type" value={form.visit_type} onChange={change}/></label><label>Date<input name="date" type="date" value={form.date} onChange={change} required/></label><label>Location (optional)<input name="location" value={form.location} onChange={change}/></label><label>Preparation notes (optional)<textarea name="notes" value={form.notes} onChange={change}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?'Saving…':'Save appointment'}</button></form>}
function NewAppointment(){const nav=useNavigate();return <main><h1>New appointment</h1><AppointmentForm onSave={async f=>{const d=await api('/api/appointments',{method:'POST',body:JSON.stringify(f)});nav(`/appointments/${d.appointment.id}`)}}/></main>}
function Detail(){const {id}=useParams(),nav=useNavigate(),[a,setA]=useState(null),[error,setError]=useState(''),[question,setQuestion]=useState(''),[priority,setPriority]=useState(2);const load=()=>api(`/api/appointments/${id}`).then(d=>setA(d.appointment)).catch(e=>setError(e.message));useEffect(load,[id]);if(error)return <main><p className="error">{error}</p></main>;if(!a)return <main><p>Loading appointment…</p></main>;const deleteAppointment=async()=>{if(confirm('Delete this appointment and all its questions?')){await api(`/api/appointments/${id}`,{method:'DELETE'});nav('/appointments')}};const add=async e=>{e.preventDefault();if(!question.trim())return;await api(`/api/appointments/${id}/questions`,{method:'POST',body:JSON.stringify({text:question,priority:Number(priority)})});setQuestion('');load()};const updateQ=async(q,patch)=>{await api(`/api/questions/${q.id}`,{method:'PATCH',body:JSON.stringify(patch)});load()};return <main><div className="pageTitle"><div><p className="eyebrow">{a.date}</p><h1>{a.provider}</h1><p>{a.visit_type}{a.location&&` · ${a.location}`}</p></div><div className="actions"><Link className="button secondary" to={`/appointments/${id}/edit`}>Edit</Link><button className="danger" onClick={deleteAppointment}>Delete</button></div></div>{a.notes&&<section className="notes"><h2>Preparation notes</h2><p>{a.notes}</p></section>}<section><h2>Questions to discuss</h2><form className="questionForm" onSubmit={add}><input aria-label="New question" placeholder="Add a question for your visit" value={question} onChange={e=>setQuestion(e.target.value)}/><select value={priority} onChange={e=>setPriority(e.target.value)} aria-label="Priority"><option value="1">Priority 1</option><option value="2">Priority 2</option><option value="3">Priority 3</option></select><button>Add question</button></form>{a.questions.length===0?<p className="muted">No questions yet. Add the most important concern first.</p>:<div className="questions">{a.questions.map(q=><article className={'question '+(q.discussed?'done':'')} key={q.id}><input type="checkbox" checked={q.discussed} onChange={e=>updateQ(q,{discussed:e.target.checked})} aria-label={`Mark ${q.text} discussed`}/><div><span className="badge">Priority {q.priority}</span><p>{q.text}</p></div><button className="linkButton dangerText" onClick={()=>{if(confirm('Delete this question?'))api(`/api/questions/${q.id}`,{method:'DELETE'}).then(load)}}>Delete</button></article>)}</div>}</section></main>}
function Edit(){const {id}=useParams(),nav=useNavigate(),[a,setA]=useState(null);useEffect(()=>{api(`/api/appointments/${id}`).then(d=>setA(d.appointment))},[id]);if(!a)return <main><p>Loading appointment…</p></main>;return <main><h1>Edit appointment</h1><AppointmentForm initial={a} onSave={async f=>{await api(`/api/appointments/${id}`,{method:'PATCH',body:JSON.stringify(f)});nav(`/appointments/${id}`)}}/></main>}
function Home(){const {user}=useAuth();return <main className="hero"><p className="eyebrow">Appointment preparation planner</p><h1>Arrive prepared for the conversations that matter.</h1><p>CarePrep keeps fictional appointment details and prioritized questions together in a private, simple workspace.</p><Link className="button" to={user?'/appointments':'/register'}>{user?'View appointments':'Create your workspace'}</Link></main>}
function NotFound(){return <main><h1>Page not found</h1><Link to="/">Return home</Link></main>}
function App(){return <AuthProvider><BrowserRouter><Navbar/><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/><Route path="/appointments" element={<Protected><Appointments/></Protected>}/><Route path="/appointments/new" element={<Protected><NewAppointment/></Protected>}/><Route path="/appointments/:id" element={<Protected><Detail/></Protected>}/><Route path="/appointments/:id/edit" element={<Protected><Edit/></Protected>}/><Route path="*" element={<NotFound/>}/></Routes></BrowserRouter></AuthProvider>}
createRoot(document.getElementById('root')).render(<StrictMode><App/></StrictMode>)
